{"name": "test_another_failing_t", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "@pytest.mark.development\n    @pytest.mark.production\n    def test_another_failing_t():\n>       assert 1 == 2\nE       assert 1 == 2\n\ntests/users/test_users.py:34: AssertionError"}, "start": 1659716639039, "stop": 1659716639039, "uuid": "10eadb67-fad8-45f9-9a68-5cba41650a4b", "historyId": "c098d4159369c5bb7cf0fbf505e8cc4e", "testCaseId": "03fa5500df12cbee54ff24c38616ad9a", "fullName": "tests.users.test_users#test_another_failing_t", "labels": [{"name": "tag", "value": "production"}, {"name": "tag", "value": "development"}, {"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "ivan-pc"}, {"name": "thread", "value": "47044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}