{"name": "test_another_failing_t", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "@pytest.mark.development\n    @pytest.mark.production\n    def test_another_failing_t():\n        \"\"\"\n        In that test we try to check that 1 is equal to 2\n        \"\"\"\n>       assert 1 == 2\nE       assert 1 == 2\n\ntests/users/test_users.py:40: AssertionError"}, "description": "\n    In that test we try to check that 1 is equal to 2\n    ", "start": 1659756043991, "stop": 1659756043991, "uuid": "316d90fb-0c85-4a54-b0f3-c2bc8cdf9a46", "historyId": "c098d4159369c5bb7cf0fbf505e8cc4e", "testCaseId": "03fa5500df12cbee54ff24c38616ad9a", "fullName": "tests.users.test_users#test_another_failing_t", "labels": [{"name": "tag", "value": "production"}, {"name": "tag", "value": "development"}, {"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "ivan-pc"}, {"name": "thread", "value": "7628-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}